#!/bin/sh
while true; do
    x="$(slurp -p -b '#00000000')"
    if test $? -ne 0; then
        break
    fi
    grim -g "$x" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | tail -n 1 | cut -d ' ' -f 4 | pastel color
done
