#!/usr/bin/env python
from random import random
from sys import argv
from math import floor
l = len(argv)
if l == 1:
    print(random())
elif l == 2:
    print(random() * int(argv[1]))
else:
    stderr.write("Synopsis: rand [max]. Returns a truely random number between 0 and max, or between 0 and 1 if max is not specified.\n")
