== my utils

.executable scripts

[horizontal]
archvm:: headless start of my virtualbox arch vm, so that i can ssh into it
battery-monitor:: daemon that alerts or suspends on low battery
codepoint:: get the codepoint of a character, or get a character from a codepoint (hex or dec)
color-picker:: sway-specific color picker. intended to be run from a terminal. requires `pastel(1)`
colors:: print a terminal color palette
copy-playlists-to-ext-disk:: self-explanatory. expects m3u8 playlists.
cs:: interactive color scheme selector. requires `fzf(1)`.
del-not-here:: used with e.g. `cp -rut /mnt/backup/ /home` to synchronize folders' contents, here `/mnt/backup/home` with `/home`.
extract-audio:: <obvious>
fromsexy:: converts `.Xresources` output to a format usable by `kitty(1)`. named b/c i used it for <https://terminal.sexy>'s themes
lsext:: list the extensions of a given directory (and optionally its descendants) or list files of a given extension
ow:: "open with." interactively browse files (using `fzf(1)`) and open them with a given program
parrot.hs:: a server that displays your http request
powerline:: display a powerline. also a library, and a dependency of `battery-monitor`.
rand:: get a truly random number from the terminal
searchpkgs:: search nixpkgs easily & efficiently, with pretty output
unique:: `sort -u` but preserves order.

.libraries

[horizontal]
http.rkt:: convenience functions around the `http-easy` library
json-extra.rkt:: powerful json macros & accessor functions
optimal.rkt:: given many maps with common keys, get all desired keys with the fewest map lookups
ring-buffer.rkt:: emulation of a ring buffer by vectors and modular arithmetic
time.rkt:: convenience functions around the `gregor` library
tree.rkt:: rose trees
util.rkt:: big collection of miscellaneous functions
