#!/usr/bin/env racket
#lang racket/base

;; map available inputs to used inputs (choose how to use available inputs.)
;; alternative to kanshi b/c it wasn't working for me. *shrug*
;; doesn't automatically run on output (dis)connect, but w/e just keybind it
;; in sway config.

;; TODO: doesn't disable when i run after disconnecting external displays
;; b/c swaymsg -t get_outputs doesn't tell about prior-enabled-but-currently-disconnected
;; displays. not sure if disabling disconnected displays is necessary, anyway, though.

(require json
         racket/system
         racket/match
         racket/set
         (only-in racket/port port->string)
         (only-in racket/list partition))

(define (readproc p . args)
  (match (apply process*/ports #f (current-input-port) 'stdout (find-executable-path p) args)
         [(list output _input _pid _err ask)
          (ask 'wait)
          (begin0 (port->string output) (close-input-port output))]))

(define action (make-parameter system))

(define (setoutputs . oss)
  (let ([found-outputs (for/set ([x (string->jsexpr (readproc "swaymsg" "-t" "get_outputs"))]) (hash-ref x 'name))])
    (let lp ([oss oss])
      (unless (null? oss)
        (let* ([os (car oss)]
               [out-ids (for/set ([o os]) (car (regexp-match #px"[^[:space:]]+" o)))])
          (if (subset? out-ids found-outputs)
              (begin (for ([o os])
                          ((action) (string-append "swaymsg -- output " o)))
                     (for ([o (set-subtract found-outputs out-ids)])
                          ((action) (string-append "swaymsg -- output " o " disable"))))
              (lp (cdr oss))))))))

(define given-args (vector->list (current-command-line-arguments)))
(define avail-args '(("b" "laptop below horiz monitor")))

(unless (null? (set-intersect '("-h" "--help") given-args))
  (displayln "available args:")
  (for ([A avail-args]) (apply printf "  ~a: ~a~n" A))
  (exit))

(when (member "--dry-run" given-args) (action displayln))

;; when i physically rotate monitors, swap transforms and positions
(setoutputs ;;'["HDMI-A-1 enable transform 0 position 0 0"       ;; left
            ;;  "HDMI-A-2 enable transform 90 position 1080 112" ;; right
            ;;  "eDP-1    enable position 1080 1192"]            ;; 112 + 1080

            '["HDMI-A-1 enable transform 0 position 0 0"
              "HDMI-A-2 enable transform 90 position 1920 -134"
              "eDP-1    enable position 0 1081"]

            (if (member "b" given-args)

                '["HDMI-A-2 enable position 0 0"
                  "eDP-1    enable position 0 1080"]
                '["HDMI-A-2 enable position 0 0 transform 0"])

            '["HDMI-A-1 enable"]

            '["eDP-1 enable"])
